services:
    Eltharin\InvitationsBundle\Repository\InvitationRepository:
        tags: ['doctrine.repository_service']
        arguments: [ '@doctrine' ]

    Eltharin\InvitationsBundle\Service\InvitationManager:
        arguments:
            - '@Eltharin\InvitationsBundle\Repository\InvitationRepository'
            - '@Symfony\Component\Mailer\MailerInterface'
            - '@Symfony\Component\Mailer\Transport\TransportInterface'

    Eltharin\InvitationsBundle\Controller\InvitationController:
        tags: ['controller.service_arguments', 'container.service_subscriber']
        autowire: yes
        autoconfigure: yes
